#!/usr/bin/env perl
use strict;
use File::Basename;
use File::Spec;

# Purpose: run some sanity checks before `git` actions.

my %checks_to_run = (
    'pre-commit' => [ qw(auxfiles gotests) ],
    'pre-push'   => [ qw(allcommitted govets) ],
);
my $orgpath = File::Spec->rel2abs(__FILE__);
my $hook = $orgpath;
$hook =~ s{.*/}{};

if ($orgpath =~ m{tools/}) {
    warn("\nThis should be installed in .git/hooks. You can always rerun:\n");
    for my $k (keys(%checks_to_run)) {
        warn("  ln -sf $orgpath .git/hooks/$k\n");
    }
    warn("I'll just run all pre- tests that I know of.\n\n");
}

my @hooks_to_run;
if ($hook eq 'pre-hook') {
    @hooks_to_run = sort(keys(%checks_to_run));
} else {
    @hooks_to_run = ($hook);
}

for $hook (@hooks_to_run) {
    my @checks = @{$checks_to_run{$hook}}
        or die("misconfiguration in $orgpath: no checks configured for hook $hook\n");

    for my $check (@checks) {
        my $cmd = "tools/checks/$check";
        system($cmd) and die("$hook hook failed on $cmd\n");
    }
}