#!/usr/bin/env perl
use strict;

# Purpose: check that everything is locally committed.

open(my $if, "git status |") or die("cannot run `git status`: $!\n");
my @lines;
my $all_committed;
while (my $line = <$if>) {
    push(@lines, $line);
    $all_committed = 1 if ($line =~ m{nothing to commit, working tree clean});
}
if (not $all_committed) {
    warn("allcommitted: not everything is locally committed\n");
    for my $line (@lines) {
        print("    $line");
    }
    exit(1);
}
print("allcommitted: everything is locally committed\n");
