#!/usr/bin/env perl
use strict;

my %aux = (
    'README.md'  => 'is required as a general description',
    '.gitignore' => 'must be present to ignore at least .git and .gitignore',
);

for my $f (keys(%aux)) {
    next if (-f $f);
    die("auxfiles: $f is missing: it ", $aux{$f}, "\n");
}
print("auxfiles: all helpfiles accounted for\n");