#!/usr/bin/env perl
use strict;
use File::Basename;
use File::Find;
use File::Spec;

# Purpose: check that every .go file has a test and that it works.

my $test_found;

sub wanted {
    my $f = $File::Find::name;
    # Strip leading ./ for display purposes.
    $f =~ s{^./}{};

    # Skip not interesting files.
    next unless ($f =~ m{.go$});
    next if ($f =~ m{_test.go});

    # Found a source file XYZ.go. Verify that XYX_test.go exists,
    # if not, warn about it.
    my $test = $f;
    $test =~ s{.go$}{_test.go};
    if (! -f $test) {
        warn("gotests: $f lacks a corresponding $test, add it\n");
    } else {
        # Found tests to run later
        $test_found++;
    }
}

find({
    wanted => \&wanted,
    no_chdir => 1,
},  '.');

if ($test_found) {
    print("gotests: found $test_found tests\n");
    open(my $if, "go test ./... |") or die("cannot start `go test`\n");
    my @lines;
    while (my $line = <$if>) {
        push(@lines, "    $line");
    }
    if (! close($if)) {
        for my $l (@lines) {
            print($l);
        }
        die("go test(s) failed\n");
    }
}