#!/usr/bin/env perl
use strict;
use File::Basename;
use File::Find;
use File::Spec;

# Purpose: check that every .go file has a test and that it works.

# Find the packages in this repo.
my %gomods;
open(my $if, "go test ./... |") or die("cannot start `go test`: $!\n");
for my $line (<$if>) {
    my @parts = split(/\t/, $line);
    my $mod = $parts[1];
    next unless ($mod);
    $gomods{$mod} = 1;
}

# Check the packages.
my $goterr;
for my $mod (sort(keys(%gomods))) {
    my $cmd = "go vet $mod";
    open(my $if, "$cmd 2>&1 |") or die("cannot start `go vet`: $!\n");
    my @lines;
    for my $line (<$if>) {
        next if ($line =~ m{^#});
        push(@lines, "    $line");
    }
    if (! close($if)) {
        print("govets: $cmd failed\n");
        $goterr = 1;
        for my $line (@lines) {
            print($line);
        }
    }
}

die("govets: above vetting failed\n") if ($goterr);
